### ISSUE TITLE
No header sent with request (tracing)

### ISSUE THREAD

**Issue by RemiKalbe** [TrueLayer/reqwest-middleware#25]
## Bug description

When sending a request, as I understand, a `traceparent` header should be added to the request. When sending a request, no such header is added.

Example of a dummy request
<img width="615" alt="CleanShot 2022-01-17 at 17 05 45@2x" src="https://user-images.githubusercontent.com/8604600/149811732-af536c6f-f8f8-4927-9a69-311619545e7d.png">

## To Reproduce

```rust
    let filter = EnvFilter::try_from_default_env()
        .or_else(|_| EnvFilter::try_new("info"))
        .unwrap();

    let opentelemetry_endpoint =
        env::var("OPENTELEMETRY_ENDPOINT").expect("Missing env var 'OPENTELEMETRY_ENDPOINT''");

    let exporter = opentelemetry_otlp::new_exporter()
        .tonic()
        .with_endpoint(opentelemetry_endpoint);

    let config =
        opentelemetry::sdk::trace::config().with_resource(opentelemetry::sdk::Resource::new(vec![
            opentelemetry::KeyValue::new("service.name", "gateway"),
            opentelemetry::KeyValue::new("service.namespace", "cloud-conference"),
        ]));

    let tracer = opentelemetry_otlp::new_pipeline()
        .tracing()
        .with_exporter(exporter)
        .with_trace_config(config)
        .install_batch(opentelemetry::runtime::Tokio)
        .expect("Failed to create opentelemtry pipeline");

    let telemetry = tracing_opentelemetry::layer().with_tracer(tracer);

    let subscriber = tracing_subscriber::fmt::layer()
        .json()
        .with_current_span(true)
        .event_format(tracing_bridge::TraceIdFormat);

    tracing_subscriber::registry()
        .with(telemetry)
        .with(filter)
        .with(subscriber)
        .try_init()
        .unwrap();
```
I'm using a proxy here to check if the header is present because the traces I got on grafana only included one service, so I used that proxy to debug, and I found that the `traceparent` header isn't sent.
```rust
    let reqwest = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(10))
        .proxy(reqwest::Proxy::http("172.16.6.96:9090").unwrap())
        .build()
        .expect("Failed to build reqwest");
    let reqwest = ClientBuilder::new(reqwest).with(TracingMiddleware).build();
    let reqwest = Arc::new(reqwest);
```
Then I put this reqwest client in a state, that I clone each time I want to make a request.
## Expected behavior

Having the `traceparent` header on every requests.

## Environment

- OS: macOS 12.0.1 (21A559)
- Rust version: 1.56.1

## Additional context

```toml
tracing = "0.1"
tracing-futures = "0.2"
tracing-log = { version = "0.1", features = ["env_logger"] }
tracing-subscriber = { version = "0.3.5", features = ["env-filter", "json", "fmt"] }
tracing-error = "0.2.0"
tracing-serde = "0.1.2"
tracing-opentelemetry = "0.16.0"
opentelemetry = { version = "0.16.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.9.0" }
reqwest-middleware = "0.1.3"
reqwest-tracing = { version = "0.2.0", features = ["opentelemetry_0_16"] }
```
